'use strict';
const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('fs');
const path = require('path');
const DGSearch = require('../assets/dg-search.js');

const FIXTURE = [
  { unitid: '198516', name: 'Appalachian State University', city: 'Boone', state: 'NC', website: 'https://www.appstate.edu', domain: 'appstate.edu' },
  { unitid: '157289', name: 'University of Louisville', city: 'Louisville', state: 'KY', website: 'https://louisville.edu', domain: 'louisville.edu' },
  { unitid: '206604', name: 'University of Dayton', city: 'Dayton', state: 'OH', website: 'https://udayton.edu', domain: 'udayton.edu' },
  { unitid: '135789', name: 'University of West Florida', city: 'Pensacola', state: 'FL', website: 'https://uwf.edu', domain: 'uwf.edu' },
  { unitid: '134130', name: 'University of Florida', city: 'Gainesville', state: 'FL', website: 'https://www.ufl.edu', domain: 'ufl.edu' }
];

test('search by partial name', () => {
  const r = DGSearch.search(FIXTURE, 'appstate');
  assert.ok(r.length >= 1);
  assert.strictEqual(r[0].name, 'Appalachian State University');
});

test('search by exact domain ranks first', () => {
  const r = DGSearch.search(FIXTURE, 'appstate.edu');
  assert.strictEqual(r[0].domain, 'appstate.edu');
});

test('search by city', () => {
  const r = DGSearch.search(FIXTURE, 'Louisville');
  assert.ok(r.some(i => i.domain === 'louisville.edu'));
});

test('search by state name and by state code', () => {
  const byName = DGSearch.search(FIXTURE, 'Kentucky');
  assert.deepStrictEqual(byName.map(i => i.domain), ['louisville.edu']);
  const byCode = DGSearch.search(FIXTURE, 'FL');
  assert.deepStrictEqual(byCode.map(i => i.domain).sort(), ['ufl.edu', 'uwf.edu']);
});

test('invalid search returns nothing rather than a fallback result', () => {
  assert.deepStrictEqual(DGSearch.search(FIXTURE, 'zzzzzz'), []);
  assert.deepStrictEqual(DGSearch.search(FIXTURE, ''), []);
  assert.deepStrictEqual(DGSearch.search(FIXTURE, '   '), []);
  assert.deepStrictEqual(DGSearch.search(FIXTURE, null), []);
});

test('results are capped', () => {
  assert.ok(DGSearch.search(FIXTURE, 'university', { limit: 2 }).length <= 2);
});

test('state code resolution', () => {
  assert.strictEqual(DGSearch.stateCodeFor('north carolina'), 'NC');
  assert.strictEqual(DGSearch.stateCodeFor('nc'), 'NC');
  assert.strictEqual(DGSearch.stateCodeFor('nowhere'), null);
});

/* The real directory is generated by scripts/import-institutions.js. When it is
   present these tests assert its shape; they skip (not fail) when it is not, so
   the suite is meaningful both before and after the import runs. */
const DIR = path.join(__dirname, '..', 'assets', 'data', 'institutions.json');
/* The file ships empty until the official import runs, so "has a directory"
   means "has rows", not merely "the file exists". */
const hasDirectory = (() => {
  try { return JSON.parse(fs.readFileSync(DIR, 'utf8')).length > 0; } catch (_) { return false; }
})();

test('institution dataset loads and has the documented shape', { skip: hasDirectory ? false : 'directory not imported yet (run: npm run import:institutions)' }, () => {
  const data = JSON.parse(fs.readFileSync(DIR, 'utf8'));
  assert.ok(Array.isArray(data) && data.length > 0);
  const keys = ['unitid', 'name', 'city', 'state', 'website', 'domain'];
  for (const inst of data.slice(0, 200)) {
    assert.deepStrictEqual(Object.keys(inst).sort(), keys.slice().sort());
    assert.ok(inst.name && inst.domain, 'name and domain are always present');
    assert.match(inst.domain, /^[a-z0-9-]+(\.[a-z0-9-]+)+$/);
    assert.match(inst.state, /^[A-Z]{2}$/);
  }
  const domains = data.map(i => i.domain);
  assert.strictEqual(new Set(domains).size, domains.length, 'domains are unique');
});

test('real directory is searchable by name, domain and state', { skip: hasDirectory ? false : 'directory not imported yet (run: npm run import:institutions)' }, () => {
  const data = JSON.parse(fs.readFileSync(DIR, 'utf8'));
  const sample = data[Math.floor(data.length / 2)];
  assert.ok(DGSearch.search(data, sample.domain).some(i => i.unitid === sample.unitid));
  assert.ok(DGSearch.search(data, sample.name).some(i => i.unitid === sample.unitid));
  assert.ok(DGSearch.search(data, sample.state, { limit: 5000 }).some(i => i.unitid === sample.unitid));
});
